name: Deploy on push
on: 
  push:
  workflow_dispatch: 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: echo ${{ secrets.SSH_HOST }}
      #  run: ssh-keyscan -H # 43.206.110.168:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
|1|lpOARwPDqK3c8u4rjApNFKlg/NQ=|FdF+m+MtselX249hmbRft4HjFIk= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDMBkrhEXB9sYr20021Jm+xZ/Ghco6GmeatOCWwQBro+g4Ma5feQzrWFJ4SdclHCkRDK10GSiRHAkuJH9ky52IvnwNtgEJxkimEvOj1cxfhtC2BbGVqYAl5t+woehx1Y2P0+xhIj/TEno3Rz+S46KDLKkeHe95uiCsJ5gCn3FlQfKUCaD8KBxb9I6hE04OdAzI8TnarUwDCd611VL9krpx0pHRXj/glHygzNUcA5ojTnlv8PSRHY8vuywnVRJW7BViJQbMF5JpCvr3O6n+WAM3cBjlR9b07CAlsWrarspAhdoEQZvqOe3GKrLMRJnMcDHQYXNDI9JnrsW68AoF5kEeD4a2tUKDcaQMg2OFWgvQ/73xcB+8kS3qAL7edvdejxN8RTUQzFihARQhV6RMKK6z6aosULOd38vVYyAhUey8b+s+L7Yj9+86dn8xK+eMIhaFLvdYvAxXkGw6LO7yETQAWKEdwt9MEuW43A6vckyvbdNxNyLnPG2takr+RcHkxEYU= >> ~/.ssh/known_host
    #  - name: Deploy with rsync
    #    run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/dist/  
